# Generated by Django 5.1.7 on 2025-03-28 02:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('cedula', models.BigIntegerField(unique=True)),
                ('fecha_nacimiento', models.DateField()),
                ('estado_asistencia', models.CharField(choices=[('Presente', 'Presente'), ('PP3', 'Permiso personal por tres horas'), ('PP4', 'Permiso personal por cuatro horas'), ('CC', 'Cambio de contrato'), ('PR', 'Permiso remunerado'), ('PNR', 'Permiso no remunerado'), ('IL', 'Incapacidad laboral'), ('IG', 'Incapacidad general'), ('PM', 'Permiso de maternidad'), ('PP', 'Permiso de paternidad'), ('LT15', 'Llegada tarde por 15 minutos'), ('L', 'Licencia'), ('FSS', 'Falta sin soporte'), ('CD', 'Calamidad doméstica'), ('SP', 'Suspendido'), ('SC', 'Sin contratar'), ('CM', 'Cita médica')], max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
