# Generated by Django 5.1.7 on 2025-04-24 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalAPP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='estado_asistencia',
            field=models.CharField(choices=[('Presente', 'Presente'), ('PP3', 'Permiso personal por tres horas'), ('PP4', 'Permiso personal por cuatro horas'), ('CC', 'Cambio de contrato'), ('PR', 'Permiso remunerado'), ('PNR', 'Permiso no remunerado'), ('IL', 'Incapacidad laboral'), ('IG', 'Incapacidad general'), ('PM', 'Permiso de maternidad'), ('PP', 'Permiso de paternidad'), ('LT15', 'Llegada tarde por 15 minutos'), ('L', 'Licencia'), ('FSS', 'Falta sin soporte'), ('CD', 'Calamidad doméstica'), ('SP', 'Suspendido'), ('SC', 'Sin contratar'), ('CM', 'Cita médica')], default='Presente', max_length=50),
        ),
    ]
